#!/usr/bin/env python3

from bs4 import BeautifulSoup
import decorating as dc
from decorating.color import colorize
from oiprog_helper import thailandoi, oichecklist, codeforces
from oiprog_helper.config import set_config, init
from oiprog_helper.style import txt, number, error, help
import sys
from tinydb import TinyDB, Query, where

@dc.writing(delay=0.005)
def printer(res) :
    if res == None :
        return
    if ('thailandoi' in res) :
        thailandoi.display(res['thailandoi'])
    if ('oichecklist' in res) :
        oichecklist.display(res['oichecklist'])
    if ('codeforces' in res) :
        codeforces.display(res['codeforces'])

def Crawl () :
    try :
        res = {}

        db = TinyDB('./db.json')
        Config = Query()

        toi = db.search(Config.thailandoi.exists())[0]['thailandoi']
        oic = db.search(Config.oichecklist.exists())[0]['oichecklist']
        cf = db.search(Config.codeforces.exists())[0]['codeforces']

        if (toi['display']) :
            with dc.animated("Crawling back to you~") :
                res['thailandoi'] = thailandoi.get()

        if (oic['display']) :
            with dc.animated("We bout to go up, baby up we go~") :
                res['oichecklist'] = oichecklist.get()

        if (cf['display']) :
            with dc.animated("Let it be~") :
                res['codeforces'] = codeforces.get()

        return res
    except Exception as e :
        # print(e)
        error()
        return 

if len(sys.argv) > 1 :
    if len(sys.argv) == 2 and sys.argv[1] == 'config' :
        set_config()
    elif len(sys.argv) == 2 and sys.argv[1] == 'init' :
        init()
    elif len(sys.argv) == 2 and sys.argv[1] == 'help' :
        help()
    else :
        print("Command not found : `oiprog help` to learn more")
else :

    printer(Crawl())
