#!/usr/bin/env python3

from bs4 import BeautifulSoup
import decorating as dc
from decorating.color import colorize
from oiprog_helper import thailandoi, oichecklist, codeforces
from oiprog_helper.config import config
from oiprog_helper.style import txt, number, error

@dc.writing(delay=0.005)
def printer(res) :
    if res == None :
        return
    if ('thailandoi' in res) :
        thailandoi.display(res['thailandoi'])
    if ('oichecklist' in res) :
        oichecklist.display(res['oichecklist'])
    if ('codeforces' in res) :
        codeforces.display(res['codeforces'])

def Crawl () :
    try :
        res = {}

        if (config['thailandoi']['display']) :
            with dc.animated("Crawling back to you~") :
                res['thailandoi'] = thailandoi.get()

        if (config['oichecklist']['display']) :
            with dc.animated("We bout to go up, baby up we go~") :
                res['oichecklist'] = oichecklist.get()

        if (config['codeforces']['display']) :
            with dc.animated("Let it be~") :
                res['codeforces'] = codeforces.get()

        return res
    except Exception as e :
        error()
        return 

config['thailandoi']['url'] = 'https://evaluator.thailandoi.org/login/login?utf8=%E2%9C%93&authenticity_token='+config['thailandoi']['authen_token']+'&login='+config['thailandoi']['user']+'&password='+config['thailandoi']['pwd']+'&commit=Login'
config['codeforces']['urlstatus'] = 'https://codeforces.com/api/user.status?handle='+config['codeforces']['handle']
config['codeforces']['urlrating'] = 'https://codeforces.com/api/user.rating?handle='+config['codeforces']['handle']

printer(Crawl())
